server:
  port: 8386
  servlet:
    context-path: /v1
spring:
  main:
    allow-circular-references: true
  application:
    name: eduPrime-server
  zipkin:
    base-url: http://localhost:9411/
#  cloud:
#    config:
#      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/edu_prime
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      auto-commit: false
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        type: uuid-char
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
#      host: redis-19270.c114.us-east-1-4.ec2.redns.redis-cloud.com
#      port: 19270
#      username: default
#      password: 75WB7ibmyYVXHbCtzR4tRf1yJUpyxIDv

service:
  name: eduPrime-server

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

jwt:
  expiration: 2592000 #30days = 30*24*60*60
  expiration-refresh-token: 5184000 #60days
  secret: elearninguserservicenjvnvnsjvdvnsvnsvsjvnsvjdvn5AldNYDhCaiCmGiLDDmsmsmfvndvnsdvnsdvnsvnsdvnksvnksdvndjsvnsdkvnskvsjkvsvjkvbkjsdvskvsvbdvdvn

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

open:
  api:
    title: API Edu
    version: v1.0.0
    description: Mo ta
    serverUrl: http://localhost:8386/v1
    serverName: edu-prime

cache:
  ttl:
    min: 7
    max: 10

file:
  upload-dir:
    image: uploads/images
    video: uploads/videos

baseUrl:
  local:
    view-image: http://localhost:8386/v1/images/
  server: null